### ISSUE TITLE
the binary is not available to download on the github release page

### ISSUE THREAD

**Issue by ginader** [ThePacielloGroup/CCA-OSX#15]
Only the source is listed there. This is likely to confuse folks who are not familiar with github.

**Comment by ferllings** [comment]
The binary are available for the beta version. But not for the oldest. I'm going to add it.
Thanks

**Comment by ginader** [comment]
this page is linked from the apps website: https://github.com/ThePacielloGroup/CCA-OSX/releases/latest

**Comment by ferllings** [comment]
Yes, it should be https://github.com/ThePacielloGroup/CCA-OSX/releases
