### ISSUE TITLE
Picks wrong color from Photoshop

### ISSUE THREAD

**Issue by chrleon** [ThePacielloGroup/CCA-OSX#21]
I have some swatches of color defined in a branding manual. When I pick from those colors in Photoshop, the HEX-values are changed. Like #73d1ff is turned into #6fd0ff when picked from Photoshop. The PSD file is sRGB. The Displays are set to sRGB profiles.

Other colorpickers pick the correct colors from Photoshop. but not CCA-OSX.

**Comment by ferllings** [comment]
Do you use the version 1.5.x ?

**Comment by uxjam** [comment]
Just noticed the same problem here. Not just Photoshop, seems to be any program. Not 100% of colors are wrong, but a lot. Ex: if I color-pick the red "bug" label off to the right side of the screen here on Git, I get #FB0016 even though the CSS source says #FC2929. I've been using this tool for a few years and am now wondering if it's been wrong all along and I just never noticed, or if this is a recent problem...

Running CCA version 1.5.13 on MacBook Pro mid-2015 Retina, OSX Yosemite

**Comment by ferllings** [comment]
Yes, This is a well know issue in 1.5.\* 
That's why this version has been removed from the release list.

The problem, is that the OSX standard Color Picker, is influenced by the user Color Profile.
I was never able to find a way around, so I decided to build a color picker from scratch.

I suggest you to try the version https://github.com/ThePacielloGroup/CCA-OSX/releases/tag/2.0-beta1, which I think is the only one working on Yosemite

**Comment by ssollinger** [comment]
I have the same issue using version 2.3 (0).
The colour picker is giving me wrong values, depending on the color profile in use. 
A good test page is this: http://www.color-hex.com/popular-colors.php
Check e.g. blue, red, green - on my system blue is quite a lot off:
![screen shot 2016-09-21 at 16 40 36](https://cloud.githubusercontent.com/assets/22349753/18718116/33add396-801a-11e6-80b9-54c4552ca95a.png)

I use the built-in Digital Color Meter in OS X which allows me to select a different color profile. I found for me "Display in sRGB" works best and is very accurate, but of course this depends on the actual color profile chosen on a system. Maybe you can allow users to select a color profile to correct these errors?

(forgot to add: I'm on OS X El Capitan)

**Comment by mhtpn** [comment]
I have the same issue on 2.3 in El Capitan. Even when picking colours already picked by CCA, it seems to converge to specific colours. See gif: 
![contrastanalyzer](https://cloud.githubusercontent.com/assets/15685320/20139766/0933e076-a688-11e6-9cbf-1e75c1ee13c7.gif)

**Comment by ferllings** [comment]
Thanks for the gif.
I'm able to reproduce it. I'll investigate.
