### ISSUE TITLE
Contrast ratio and rounding

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-OSX#23]
Following discussion here https://github.com/w3c/wcag/issues/200#issuecomment-255457358 there is/will be an issue with the way in which CCA currently rounds results to single decimal point and then uses the rounded value for its pass/fail determination.

4.5:1 and 3:1 need to be treated as absolute thresholds, and the non-rounded result needs to be assessed against this contrast. so for instance 4.49124578:1 needs to fail as it is below 4.5:1 in absolute terms - it can't be rounded first to 4.5:1 and THEN compared to the threshold figure.

this may require some extra tweaking of the displayed text for these cases. Maybe for values that are between 4.45 - 4.4999999 (or whatever the precision internally is) the output should read "The contrast ratio is: just below 4.5:1" (and the same for 2.95 - 2.9999 for the 3:1 ratio)

xref https://github.com/ThePacielloGroup/CCA-Win/issues/30

**Comment by caiters** [comment]
This just bit us today :( I was able to download an updated windows version for myself, but our designer is on Mac and his is still rounding up.

**Comment by ferllings** [comment]
Yes, sorry about that.
I'll try to find some time to update the rounding asp.
