### ISSUE TITLE
Color Contrast Analyser tool in iMac (desktop)

### ISSUE THREAD

**Issue by NamKot** [ThePacielloGroup/CCA-OSX#24]
*_Color Contrast Analyser tool in iMac (desktop) *_ 
- Noticed discrepancies in the color code picked directly from HTML rendered in browser. 
- Attached example shows three different values for Firefox, Chrome and Safari browsers for the same color point. (sample source code is included in the screenshot).
- This occurs on iMac desktop only and not on Macbook (laptop). 
  ![image](https://cloud.githubusercontent.com/assets/23038241/19659944/ea1b7fc0-99fb-11e6-90c2-983e93b0ab26.png)

**Comment by ferllings** [comment]
Thanks for the ticket.

I can't really read the source code, your image is too small.
But you can attach it on the ticket, so I can test it myself.

Is the discrepancies only on Firefox?

**Comment by NamKot** [comment]
I have attached a sample source code and image of the discrepancies across browsers. 
We have observed the discrepancies on Safari and Chrome and in most cases Firefox picks the right color. 

[index.txt](https://github.com/ThePacielloGroup/CCA-OSX/files/551030/index.txt)

![capture](https://cloud.githubusercontent.com/assets/23038241/19692668/c126b71e-9aa6-11e6-846e-d5afa631868b.PNG)

**Comment by patrickhlauke** [comment]
I'll hazard a guess that this is due to color management issues, with Firefox not following the correct ICC profile? (which would then result in Firefox explicitly showing the correct HEX values as per the document, whereas Safari/Chrome would first color-correct them and then output them)

**Comment by dfearnley** [comment]
I have found this issue on my MacBook Pro ( Sierra 10.12.3 ).  The colour picker will select three different colours from Safari, Chrome, and Firefox - Firefox being the only one where the colour picker is correct.

You might say it's the browsers, but you can try another interesting test.  Put some random colour other than pure white or black in the text box in CCA.  Now use CCA to sample its own colour panel and note that the colour samples lighter.  You can repeat this process until you eventually get to white (#FFFFFF).  This will happen even if your starting colour is #000003.

For comparison purposes, I see none of this behaviour on my Windows 7 box.
