### ISSUE TITLE
Simple slider to keep hue and only change value

### ISSUE THREAD

**Issue by 7mary4** [ThePacielloGroup/CCA-OSX#26]
I don't want to look a gift horse in the mouth, but...
I loved the older version's simple method to take an existing color and simply change the value to achieve an accessible version. This was especially helpful when the original color was around 3.5:1 and just needed to be bumped up/down. 
The current version requires us to balance rgb values. Is it possible to bring back the original slider as an alternate adjustment?

Otherwise, thank you for continuing to provide a great resource.

**Comment by ferllings** [comment]
@7mary4 The older version has exactly the same RGB sliders.
But you're right hue values would be easier to find accessible values.
We are considering this for some time now (#12), and I hope I can find some time to implement it very soon.

**Comment by l-i-n-k** [comment]
@ferllings I disagree. The old version offered the OS X COlor Picker instead of a custom picker and using the color palette we could access all sorts of color sliders and color palettes installed.

**Comment by ferllings** [comment]
Sorry I should have explained why I did it: The problem with the native OSX Color Picker is that the color value is adjusted using your color profile. I had a lot of values variations.

**Comment by JaaaPeee** [comment]
Good morning.
I have received a series of updates and closed case numbers. Does this mean that an updated version is ready for download? One that I didn’t see was a mention of my alignment issue when going from Mac to PC monitor. Has this been addressed?
Julien

**Comment by ferllings** [comment]
Yes, you test this version:
https://github.com/ThePacielloGroup/CCA-OSX/releases/tag/2.4

I've asked some people to test it before making it official

**Comment by JaaaPeee** [comment]
First basic test seems to work, as far as cursor alignment.
More testing to follow.
Julien
