### ISSUE TITLE
Picker is way off on monitor

### ISSUE THREAD

**Issue by JaaaPeee** [ThePacielloGroup/CCA-OSX#28]
I have downloaded the current version and am working on a Mac Pro, on OS Sierra 10.12.5.
When I try to use the picker, it lands about 3.5” above the object I’m trying to measure.
Is there a way to make this align properly?

**Comment by ferllings** [comment]
I noticed this bug, when using a secondary monitor.
Do you use a 2nd monitor or is it on the main monitor?

**Comment by JaaaPeee** [comment]
Yes, it is on secondary monitor. To pass the 508 requirements, we must test on a PC monitor rather than a hi-res Mac monitor.

**Comment by ZoeBijl** [comment]
Can confirm this is happening on secondary monitor.

**Comment by JaaaPeee** [comment]
Confirmation wasn’t my major interest. . . solution is what I really need. This tool is useless for me with this problem.
Julien

**Comment by ferllings** [comment]
Duplicate of https://github.com/ThePacielloGroup/CCA-OSX/issues/9
