### ISSUE TITLE
Broken button (magnifying glass)

### ISSUE THREAD

**Issue by weboverhauls** [ThePacielloGroup/CCA-OSX#34]
I think the magnifying glass button is broken. Shouldn't it open the color eyedropper when clicked? Nothing happens when I do.
![image](https://user-images.githubusercontent.com/473400/31781728-2e502f2e-b4c7-11e7-9d5e-b6eea9286b26.png)

**Comment by mattcoxonline** [comment]
Same problem here too.

**Comment by MaffooBristol** [comment]
Same issue. Looking at the xcode project, it seems that it should have a bit that slides out from that button that says "colour picker" but it doesn't. Or at least that's what I think I can see- not a MacOS developer...

Is this an issue for only this version?
Update, just checked and yes it is. Version 2.3 works fine
