### ISSUE TITLE
Color picker alignment

### ISSUE THREAD

**Issue by julzmon** [ThePacielloGroup/CCA-OSX#9]
It samples colors about 500px below the center of the Lupe.
![screen shot 2015-05-21 at 1 52 14 pm](https://cloud.githubusercontent.com/assets/46877/7755270/dc39acfa-ffc0-11e4-8d5d-b539d16a082e.jpg)

**Comment by ssollinger** [comment]
I have the same issue.
OS X El Capitan with CCA version 2.3 (0).

I only have the issue on a 2nd monitor, on my main screen (MacBook screen) the position is correct. The position seems to be off vertically by roughly the height of the first monitor, i.e. it doesn't calculate the position correctly on the 2nd monitor.
